### ISSUE TITLE
Arduino Day landing page

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#1]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**
Add a new page for arduino day, by creating a new directory called pages and including the same inside it. Requiring a landing page for the same.

**Comment by mohitrajane** [comment]
I am working on it

**Comment by mohitrajane** [comment]
It has been done. Close issue?
