### ISSUE TITLE
Add modals for agenda timeline events

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#12]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [x] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

After the requested fixes have been made in #11, we need to implement modals for each of the event in the timeline. Like display the modal on clicking/hovering the item.

Modal template idea:
### Event Heading
brief explanation about the event
### Speakers
if any
### Registration
How to register/attend, link to form(if any)
### Time&Venue
need to be specific
### Whom to contact
Will update after getting volunteer list

**Comment by mohitrajane** [comment]
i don't think venue and time required, since it is  already specified in the timeline
