### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by Tangerine98** [fisatsdc/fsdc#16]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**

Add a footer for arduino.html
Should contain "Organized by FSDC" and the FSDC logo.

**Comment by yedhink** [comment]
@Tangerine98 i can take this up.
