### ISSUE TITLE
Arduino day page add speakers into the layout

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#2]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**
Add a layout to specify the speakers for the event.

**Comment by mohitrajane** [comment]
This should be done inside the modal of each event right, so #12 also includes this and think this issue should be closed.

**Comment by yedhink** [comment]
yes. closing the issue
