### ISSUE TITLE
the agenda text on mobile gets wrapped to new line 

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#23]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**
The agenda text current wraps to a new line on reduction of space. So should we reduce the font size depending on the phone size so as to make the agenda text fit in one single line?

**Comment by yedhink** [comment]
![Screenshot_20190309_183208](https://user-images.githubusercontent.com/31244999/54071986-85e0a680-429a-11e9-9cf9-f19f52aab7d7.png)

**Comment by mohitrajane** [comment]
i couldn't replicate this issue with the same settings 
![Screenshot from 2019-03-10 23-56-24](https://user-images.githubusercontent.com/25960817/54089570-4a280880-4390-11e9-9c1f-575c8c2b998c.png)

**Comment by mohitrajane** [comment]
should this be closed?
