### ISSUE TITLE
Timeline font

### ISSUE THREAD

**Issue by Tangerine98** [fisatsdc/fsdc#24]
**This issue relates to one or more of the following:**

- [x] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

Font of Talk with Arduino Expert is smaller compared to the font of the other events on the timeline.

**Comment by mohitrajane** [comment]
Ill work on it
