### ISSUE TITLE
Modal Issues in Arduino Day page

### ISSUE THREAD

**Issue by Tangerine98** [fisatsdc/fsdc#27]
**This issue relates to one or more of the following:**

- [x] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

1. No need for border
2. Close modal by clicking on overlay
     i.e. As of now, modal closes only if it is clicked on the close button. It won't close if it is clicked somewhere else outside the modal. It would be good if that can be implemented.
3. Make the content of the modal centre aligned.
4. No need for horizontal scroll.
    i.e. When opened in desktop, a horizontal scroll appears at the bottom of the modal which is not required.
5. Change colour of modal.
6. Apply animation to register button.

**Comment by yedhink** [comment]
you can take this up.

**Comment by Tangerine98** [comment]
I'll do this.
