### ISSUE TITLE
Create timeline for agenda in new arduino day page

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#3]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**
Move the agenda from fsdc page to new arduino day page and make it as a timeline layout.

**Comment by mohitrajane** [comment]
ill work on it
