### ISSUE TITLE
popup in map should autoclose within 2 secs or so

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#31]
**This issue relates to one or more of the following:**

- [x] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**
Map popup for directions to fisat should close within few secs automatically or when clicked outside the container.

**Comment by mohitrajane** [comment]
ill work on it

**Comment by mayankpawar25** [comment]
I'll fix this bug
