### ISSUE TITLE
Issue when clicking hackaton in Timeline

### ISSUE THREAD

**Issue by mohitrajane** [fisatsdc/fsdc#38]
**This issue relates to one or more of the following:**

- [x ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

The page hangs due to data-target="#".

**Comment by mohitrajane** [comment]
Ill fix it

**Comment by yedhink** [comment]
This is a major bug. The issue remains some more items like Inauguration etc. Do test each case and make a pr.
