### ISSUE TITLE
Image not centred in modal in mobile view

### ISSUE THREAD

**Issue by mohitrajane** [fisatsdc/fsdc#39]
**This issue relates to one or more of the following:**

- [x ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**

The circular image is not centred in mobile view in modal
![Screen Shot 2019-03-11 at 17 25 55](https://user-images.githubusercontent.com/25960817/54122349-ccf9a380-4422-11e9-9859-a482209f3e0a.png)

**Comment by yedhink** [comment]
will do this.
