### ISSUE TITLE
Add an animation to the landing page of fsdc

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#4]
**This issue relates to one or more of the following:**

- [ ] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [x] Proposal to the Repository/New Feature

**Details:**
Some wireframe animation or less memory consuming animation that can go neatly with the landing page of fsdc required.

**Comment by Tangerine98** [comment]
Have few suggestions to who ever takes this up.. You can add the following:-
- For Register button : https://codepen.io/seanmccaffery/pen/xBpbG
- For hamburger menu : https://codepen.io/Zaku/pen/vcaFr
- Drop-down menu : https://codepen.io/jchoura/pen/yYeQdz
- Pre-loader : https://codepen.io/imjasonmiller/pen/WvKLor
- Carousel : https://codepen.io/MAW/pen/eyWvmj

**Comment by yedhink** [comment]
@Tangerine98 these are good. Do you think that you can find a good animation or svg that can blend in with the current fsdc landing page background?

**Comment by yedhink** [comment]
ill take this.
