### ISSUE TITLE
Hamburger menu persists even after clicking on an item

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#41]
**This issue relates to one or more of the following:**

- [x] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**
In mobile view when clicking any of the items in the hamburger menu, the menu should automatically close and the view should change to the corresponding view of the item. Currently the hamburger menu still persists even after clicking on an item.

Issue found for fsdc and arduino page.

**Comment by mohitrajane** [comment]
ill work on it

**Comment by yedhink** [comment]
@mohitrajane first fix your pr #42 then you can start working on this.

**Comment by mohitrajane** [comment]
found a fix for this but it break's the registration menu :( @Tangerine98  or @yedhink  Can u help me with  it
