### ISSUE TITLE
nav dropdown from hamburger menu doesnt close when clicking somewhere else

### ISSUE THREAD

**Issue by yedhink** [fisatsdc/fsdc#47]
**This issue relates to one or more of the following:**

- [x] Bug in the existing codebase
- [ ] Update to an code section/method
- [ ] Errors like run time errors or formatting errors
- [ ] Proposal to the Repository/New Feature

**Details:**
The nav-dropdown doesn't close when clicking somewhere else.

**Comment by mohitrajane** [comment]
ill work on it
